services:
  db:
    image: 'mysql:8.0' # Versione specifica per stabilità
    container_name: 'guide-mysql'
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'verysecret'
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: 'user-crud-app'
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Nota: qui usiamo 'db' come hostname perché Docker risolve i nomi dei servizi
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret